// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBNOa04kQWLjj7qb95AhIhLZibyXW-L2s',
    appId: '1:1033653388765:web:a4e3d2031f9f5bae0c2234',
    messagingSenderId: '1033653388765',
    projectId: 'ecofamid-122',
    authDomain: 'ecofamid-122.firebaseapp.com',
    storageBucket: 'ecofamid-122.appspot.com',
    measurementId: 'G-0Z43LNYF3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvIA_GAiDI-lBODSiE62dx6NGetj-XtA4',
    appId: '1:1033653388765:android:828b48a1382e200f0c2234',
    messagingSenderId: '1033653388765',
    projectId: 'ecofamid-122',
    storageBucket: 'ecofamid-122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgQWu9akb0uWO1N4rfWe2M2dNxmCZhLUw',
    appId: '1:1033653388765:ios:906a97a9fdda56380c2234',
    messagingSenderId: '1033653388765',
    projectId: 'ecofamid-122',
    storageBucket: 'ecofamid-122.appspot.com',
    iosClientId: '1033653388765-tds7229okcbbrt00bv966j0v5n4t1d0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgQWu9akb0uWO1N4rfWe2M2dNxmCZhLUw',
    appId: '1:1033653388765:ios:906a97a9fdda56380c2234',
    messagingSenderId: '1033653388765',
    projectId: 'ecofamid-122',
    storageBucket: 'ecofamid-122.appspot.com',
    iosClientId: '1033653388765-tds7229okcbbrt00bv966j0v5n4t1d0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );
}
